language: node_js
node_js:
  - "6"
  - "4"

#Build settings for node-fibers
env:
  - CXX=g++-4.8

#Build settings for node-fibers
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
